### PR TITLE
ui fix for selecting same token pair. closes #24

### LINKED ISSUE #24: UI disables selecting same token for buy and sell
@p-s-dev:

>Currently MM allows the same asset/token to be selected for both the Buy and Sell side of a trade.  This might result in a user accidentally doing something like selling 2eth for 1eth.

>Proposed fix options: 
> - When an asset is select from either the buy or sell side, some javascript action will remove it from the >other side.
> - Or add a validation check so that if an asset is selected and it is the same as the other side of the trade, disable the buttons for making a new trade.

---
(ported from [ UI disables selecting same token for buy and sell #131 ](https://github.com/MakerDAO/maker-otc/issues/131))

### PR DESCRIPTION
**Pull request by sunfeld**

### CODE REVIEW

File: frontend/imports/ui/client/widgets/neworder.js [hunk 1]
```diff
@@ -130,7 +130,9 @@ Template.neworder.viewmodel({
       const total = new BigNumber(this.total());
       const maxTotal = new BigNumber(this.maxTotal());
       const marketOpen = Session.get('market_open');
-      return marketOpen && price.gt(0) && amount.gt(0) && total.gt(0) &&
+      const validTokenPair = (Session.get('quoteCurrency') != Session.get('baseCurrency') ? true : false);
+      console.info(validTokenPair);
```
Comment (jorisbontje) [inline frontend/imports/ui/client/widgets/neworder.js]: Oops, you have a stray console.log here
